---
title: "References"
author: "Sandy Pullen"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# References

Alexander A (2006) Kempton, The Companion to Tasmanian History, https://www.utas.edu.au/library/companion_to_tasmanian_history/K/Kempton.htm, accessed 16 April 2022.

Annual Reports & Strategic Plans (n.d.) Southern Midlands Council, https://www.southernmidlands.tas.gov.au/annual-reports-strategic-plan/, accessed 18 May 2022.

Export with CSV Export plugin (2022) Tropy Documentation, https://docs.tropy.org/other-features/export-with-plugins, accessed 31 May 2022.

Gandhi U (2022) Georeferencing Topo Sheets and Scanned Maps, QGIS Tutorials and Tips, https://www.qgistutorials.com/en/docs/3/georeferencing_basics.html, accessed 25 May 2022.

—— (n.d.) Web Mapping with QGIS2Web (QGIS3), QGIS Tutorials and Tips, https://www.qgistutorials.com/en/docs/3/web_mapping_with_qgis2web.html, accessed 26 May 2022.

Green Ponds Progress Association (2015) Green Ponds Progress Association, https://www.greenpondsprogress.com, accessed 29 May 2022.

Heritage Documents, Reports & Strategy Plans (n.d.) Southern Midlands Council, https://www.southernmidlands.tas.gov.au/heritage-documents/, accessed 18 May 2022.

‘Heritage Highway’ (n.d.) Destination Southern Tasmania, https://hobartandbeyond.com.au/places/heritage-highway/, accessed 26 May 2022.

Heritage Projects & Sites (n.d.) Southern Midlands Council, https://www.southernmidlands.tas.gov.au/heritage-projects-and-sites/, accessed 26 May 2022.

Historic Registry of Deeds Search (2017) Land Information System Tasmania, https://www.thelist.tas.gov.au/app/content/property/historic-deeds-search.

History (2015) Green Ponds Progress Association, https://www.greenpondsprogress.com/history, accessed 16 April 2022.

Horse Drawn Heritage (n.d.) Southern Midlands Council, https://www.southernmidlands.tas.gov.au/horse-drawn-heritage/, accessed 26 May 2022.

Kempton Watch House (n.d.) Southern Midlands Council, https://www.southernmidlands.tas.gov.au/kempton-watch-house/, accessed 26 May 2022.

Land Records - CSV (n.d.) Data.gov.au, https://data.gov.au/dataset/ds-dga-4940b8e0-a2b4-49e6-b658-b124d98e2082/distribution/dist-dga-d55b564e-8cee-4642-beec-3d14a46b1536/details?q=, accessed 13 April 2022.

Libraries Tasmania - AF819-1-149 (n.d.), https://stors.tas.gov.au/AF819-1-149, accessed 5 May 2022.
LISTmap (2021) Land Information System Tasmania, https://maps.thelist.tas.gov.au/listmap/app/list/map, accessed 25 May 2022.

Maheshwari V (2022) How to locally save an image using Urllib, Educative: Interactive Courses for Software Developers, https://www.educative.io/edpresso/how-to-locally-save-an-image-using-urllib, accessed 27 May 2022.

Oatlands Community Association (n.d.) Oatlands Community Association, https://oatlandscommunity.org.au/, accessed 29 May 2022.

Pandas read_csv() - How to read a csv file in Python - Machine Learning Plus (2021) Machine Learning +, https://www.machinelearningplus.com/pandas/pandas-read_csv-completed/, accessed 27 May 2022.

Placenames Tasmania (n.d.) Placenames Tasmania, https://www.placenames.tas.gov.au/#p1, accessed 26 May 2022.

Ritchie G (2015) ‘On The Convict Trail: Green Ponds Store, Kempton’, On The Convict Trail, http://ontheconvicttrail.blogspot.com/2015/03/green-ponds-store-kempton.html, accessed 30 May 2022.

RStudio IDE Tools for reticulate (n.d.) RStudio, https://rstudio.github.io/reticulate/articles/rstudio_ide.html#line-by-line-execution, accessed 2 May 2022.

Shadows of the Past (n.d.) Southern Midlands Council, https://www.southernmidlands.tas.gov.au/shadows-of-the-past/, accessed 26 May 2022.

Southern Midlands Council (2020) Southern Midlands Council, https://www.southernmidlands.tas.gov.au/, accessed 18 May 2022.

Tasmania L (n.d.) ‘Tasmanian Land Records (1832-1935)’, https://data.gov.au/data/dataset/tasmanian-land-records-1832-1972, accessed 30 April 2022.

Tasmanian Land Records (1832-1935) (n.d.) Data.gov.au, https://data.gov.au/dataset/ds-dga-4940b8e0-a2b4-49e6-b658-b124d98e2082/details?q=, accessed 3 June 2022.

Velasquez I (2021) Three Ways to Program in Python With RStudio, https://www.rstudio.com/blog/three-ways-to-program-in-python-with-rstudio/, accessed 27 May 2022.



