---
title: "Historic Image Analysis"
author: "Sandy Pullen"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Historic Image Analysis

## Initial reflection

This comprises your initial responses to each image: does it prompt you to think about a specific issue or problem? Does it raise more questions than answers? Are there important technical or historical details that stand out to you? Are there gaps or subtle erasures in the image?

In short, for each image, address the question 'what do you see?'. Provide 1-2 sentences for each image.

Record your initial reflections in the 'Notes' field for each item.

## Structured reflection

You should decide on a set of at least ten questions that are relevant to your research focus,

1. Are there people? What are they doing?

2. What kinds of facial expressions and body language are evident in the image?

3. What is the context of the image? When and where was it taken?

4. What insights does this image provide on the past that we would not have without it?

5. 

## Presentation

a visual exhibit of your images as part of your portfolio

include a selection of images (5-10) together with narrative text. This text should explore both your initial reactions to the images and the insights to emerge from your structured analysis of them.

Use captions and ensure each image is correctly referenced, with a URL to the image source in each caption. Use formatted links rather than full URLs in text, as I generally do in these topic notes.

The aim of this discussion is to narrate the significance of these images to your research case study, and to draw out key themes of interest. Draw on your initial and structured reflections

the point of analysis is exploration of similarities and differences, trends, insights, and patterns, across the batch of images you are working on -- rather than just repeating the detailed annotations you made on each image. Finally, the images you select for your presentation should help to illustrate the main insights emerging from your image analysis, so choose carefully.

Include a link to your source data in the portfolio. This should minimally include the image reference and the questions/answers for your initial and structured reflection.
